name: Send Email on Push

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.sendgrid.net
        server_port: 587
        username: ${{ secrets.SENDGRID_USERNAME }}
        password: ${{ secrets.SENDGRID_API_KEY }}
        to: recipient@example.com
        from: your-email@example.com
        subject: "Push to GitHub"
        body: "A new push has been made to the repository!"
